Cargo.lock
azalea-nbt/Cargo.toml
azalea-nbt/benches/my_benchmark.rs
azalea-nbt/src/decode.rs
azalea-nbt/src/encode.rs
azalea-nbt/src/lib.rs
azalea-nbt/src/tag.rs
azalea-nbt/tests/tests.rs

Use AHash for HashMaps and make read_string read everything at once. I'm sure more optimizations are possible here but I don't know how to execute them. I also know I could make it way faster if it was a &[u8] instead of a Read, but it is, so I have to figure out how to optimize with that.

NBT decoder optimizations

---

azalea-client/src/client.rs
azalea-client/src/movement.rs
azalea-crypto/benches/my_benchmark.rs
azalea-protocol/src/connect.rs
azalea-protocol/src/read.rs

Previously, there was only one connection field in the client, so the protocol_loop was causing the writer to also always be locked.
This fixes it by making the client have both a reader and a writer connection, so only the reader will always be locked (which is fine since it's only used in one place).

Fix connection writer being locked

---

azalea-auth/src/cache.rs
azalea-auth/src/sessionserver.rs
azalea-brigadier/src/command_dispatcher.rs
azalea-client/src/movement.rs
azalea-world/src/chunk_storage.rs

This PR removes all println statements and logs them on the trace level instead.
Usually, libraries shouldn't print to stdout using println, since there's no control over them.
Some println statements also looked like leftover debug code, which I have removed.
I can add those back if requested.

refactor: remove println statements

---

azalea-protocol/src/packets/game/clientbound_player_info_packet.rs

This PR makes the fields in the PlayerInfo packet public.
I encountered this issue when writing my own bot which needs a list of UUID > String of all currently logged-in players, and while writing my handler for `Action::RemovePlayer` I found out that the `uuid` field is private. This PR fixes that.

fix: make fields in PlayerInfo::Action public

---

azalea-chat/Cargo.toml
azalea-chat/src/component.rs
azalea-chat/src/style.rs

We'd like to use `azalea-chat` in a custom bot to render colored text, but using the stable compiler (https://github.com/booleancoercion/ferrisquery/pull/1). We're not relying on the `azalea-buf` functionality for this so just disabling that and relying on the json serialization works fine for us. I'm not sure whether this is something you'd want to support upstream, we're fine just relying on a fork if not.
This is technically a breaking change for any users that had `azalea-chat.default-features = false` and were relying on the `azalea-buf`` functionality.

Allow using `azalea-chat` without `azalea-buf` to avoid unstable features

---

azalea-block/Cargo.toml
azalea-block/README.md
azalea-block/azalea-block-macros/Cargo.toml
azalea-block/azalea-block-macros/src/lib.rs
azalea-block/src/lib.rs

When I want to know what block is at a position, I cannot because the `Debug` impl does not not produce the name of the block. With this change, I get the desired output.

derive `Debug` for `BlockState`

---

azalea-physics/src/collision/world_collisions.rs
azalea-physics/src/lib.rs

When the bot is moving it will sometimes think it is not on the ground which will cause it to move only very slowly. The coordinates of the bounding box should be floored because that gives the correct block position.

fix `BlockCollisions` bounding box

---

azalea-client/src/disconnect.rs

Without this the bot disconnects as soon as it joins.

fix `disconnect_on_read_packets_ended`

---

azalea-protocol/src/resolver.rs

Previously, when resolving server addresses into IPs, the resolver would cause an infinite recursion if the SRV record pointed to its own domain: `_minecraft._tcp.example.com. 300 IN	SRV	30 0 25566 example.com.`.
This PR fixes that.

Fix infinite recursion in the DNS resolver

---

azalea/src/lib.rs
azalea/src/swarm/mod.rs

The current ClientBuilder implementation fails to compile unless a handler function and state are specified due to the generic values `S` and `Fut` of ClientBuilder being unable to resolve. This PR adds placeholder entries and a corresponding `no_handler()` function for ClientBuilder that allows for a more straightforward implementation when using an exclusively ECS-based codebase.
```rust
#[tokio::main]
async fn main() {
let account = Account::offline("bot");
let e = ClientBuilder::new()
.no_handler()
.add_plugins(...)
.start(account.clone(), "localhost")
.await;
eprintln!("{:?}", e);
}
```
Note that `EmptyState` and `EmptyFuture` must still be public for the code to compile, so I wrapped those in their own module. If needed, they can also be moved to a separate file, but I left them in …

no_handler() option for ClientBuilder

---

azalea/src/lib.rs

Currently, nearly all of the code used in Bot.rs is hidden, despite being written as an API. This means that components like Bot and events like LookAtEvent are inaccessible.
I think these are probably supposed to be public.

Export bot.rs

---

.gitignore
.vscode/settings.json

Usually, this folder is added to the git ignore since these settings are often customized per-user. I have edited the `settings.json` on my own local fork of the project as well based on my own extensions and utilities.

Removed .vscode settings

---

.gitignore
.vscode/settings.json
azalea-chat/src/translatable_component.rs
azalea-client/src/client.rs
azalea-client/src/local_player.rs
azalea-client/src/packet_handling.rs
azalea-entity/src/lib.rs
azalea/examples/nearest_entity.rs
azalea/src/lib.rs
azalea/src/nearest_entity.rs
azalea/src/swarm/mod.rs

This utility function (provided as a `SystemParam` for easier Bevy system integration) can be used to locate nearby entities using much less boilerplate code.
_Note that the example in this PR relies on #101 for sending LookAt events._

Created nearest_entity system param

---

azalea-protocol/src/lib.rs

Hey there,
this PR adds support for serde serialization and deserialization for the ServerAdress struct. I find this quite useful for my configuration purposes and because this library already features serde, might add this support.

Serde support for 'ServerAddress'

---

azalea-client/src/client.rs
azalea-client/src/disconnect.rs
azalea-client/src/events.rs
azalea-client/src/packet_handling/configuration.rs
azalea-client/src/packet_handling/game.rs

Hello there,
with this PR I have added the possibility to catch disconnect events and their reason easily.
But here is an issue that I am facing and cannot figure out how to fix:
When the server disconnects us from the game, we normally get `ClientboundGamePacket::Disconnect` but the connection is closed before we can read the packet and fire the event with an reason. This causes us to not get the actual disconnect message and I really need HELP with this issue.

added disconnect reason

---

Cargo.lock
azalea-client/Cargo.toml
azalea-client/src/attack.rs
azalea-client/src/client.rs
azalea-client/src/events.rs
azalea-client/src/mining.rs
azalea-client/src/movement.rs
azalea-core/Cargo.toml
azalea-core/src/lib.rs
azalea-core/src/tick.rs
azalea-entity/Cargo.toml
azalea-physics/Cargo.toml
azalea-physics/src/lib.rs
azalea-protocol/Cargo.toml
azalea-world/Cargo.toml
azalea/Cargo.toml
azalea/examples/nearest_entity.rs
azalea/src/bot.rs
azalea/src/pathfinder/mod.rs
azalea/src/pathfinder/simulation.rs
azalea/src/prelude.rs
azalea/src/swarm/mod.rs

The `FixedUpdate` schedule can run multiple times in a row without `Update` running, which can cause weird bugs under high CPU usage. This change replaces `FixedUpdate` with our own schedule that we fully control, which I chose to put in `azalea_core::tick::GameTick` (and re-export in the azalea prelude). This will likely break some plugins, but it was probably going to have to happen at some point anyways so might as well rip the band-aid off now.
I implemented the change mostly with find-and-replace, so I may have overlooked things.

Replace Bevy's FixedUpdate with Azalea's GameTick

---

azalea-core/src/particle.rs

Has all particles present on https://wiki.vg/Protocol#Particle as of 17 December 2023.
This also fixes particles being parsed as the incorrect type due to id shifts caused by newly added particles.
Please squash.

Add missing particles

---

azalea-protocol/src/packets/game/clientbound_boss_event_packet.rs

The struct itself was already public, I assume the fields where meant to be as well.

Publicize all fields on `AddOperation` and `Style`

---

azalea-auth/src/auth.rs

Example:
```
{
"items" : [ {
"name" : "game_minecraft",
"signature" : ""
}, {
"name" : "game_minecraft_bedrock",
"signature" : ""
}, {
"name" : "product_minecraft",
"signature" : ""
}, {
"name" : "product_minecraft_bedrock",
"signature" : ""
} ],
"signature" : "",
"keyId" : "1"
}
```

fix: GameOwnershipResponse key_id format

---

azalea-client/src/client.rs
azalea-client/src/ping.rs
azalea-protocol/examples/handshake_proxy.rs
azalea-protocol/src/connect.rs
azalea-protocol/src/packets/handshaking/client_intention_packet.rs
azalea-protocol/src/packets/mod.rs

Fixes #142. This is a breaking change, as seen in the tests and examples.

Use ClientIntention over ConnectionProtocol for ClientIntentionPacket

---

Cargo.lock
azalea-brigadier/Cargo.toml
azalea-brigadier/tests/bevy_app_usage.rs

Adds an example for how to use brigadier inside a bevy App.
Also fixes an issue where the `azalea_buf` feature was not enabled for `azalea_chat`.

Bevy App brigadier example

---

azalea-client/src/chat.rs
azalea-protocol/src/packets/game/serverbound_chat_command_packet.rs

I finally tracked down, why commands don't work and cause the client to disconnect.
The packet has its contents copied from the "Signed" counterpart, which is unexpected. Thus most servers kick you for it.
This should address it.
Fixes https://github.com/azalea-rs/azalea-viaversion/issues/4

Fix command packets

---

Cargo.lock
azalea-auth/Cargo.toml
azalea-block/azalea-block-macros/Cargo.toml
azalea-block/azalea-block-macros/src/lib.rs
azalea-brigadier/Cargo.toml
azalea-buf/Cargo.toml
azalea-buf/azalea-buf-macros/Cargo.toml
azalea-buf/src/read.rs
azalea-chat/Cargo.toml
azalea-chat/src/component.rs
azalea-chat/src/style.rs
azalea-client/Cargo.toml
azalea-core/Cargo.toml
azalea-core/src/lib.rs
azalea-core/src/registry_holder.rs
azalea-core/src/resource_location.rs
azalea-crypto/Cargo.toml
azalea-entity/Cargo.toml
azalea-inventory/Cargo.toml
azalea-inventory/azalea-inventory-macros/Cargo.toml
azalea-language/Cargo.toml
azalea-physics/Cargo.toml
azalea-physics/src/lib.rs
azalea-protocol/Cargo.toml
azalea-protocol/azalea-protocol-macros/Cargo.toml
azalea-registry/Cargo.toml
azalea-registry/azalea-registry-macros/Cargo.toml
azalea-world/Cargo.toml
azalea/Cargo.toml
azalea/src/lib.rs

simdnbt 0.6 rewrites `borrow` to optimize how tags are represented in memory, and fixes a memory safety issue.
Also I upgraded other deps except Bevy since that's gonna need to be a separate change.

Upgrade to simdnbt 0.6

---

azalea/build.rs

The RUSTUP_TOOLCHAIN environment variable might not always be present. This is the case for e.g. NixOS where rust is routinely not installed via rustup, thus not setting this env var, causing build failures. Instead, build.rs will now run `rustc -V` and check if the output contains the word "nightly".

Determine rust channel by parsing rustc output if env vars do not exist

---

azalea-client/src/mining.rs

This PR is similar to #156 but instead this is on main branch.
This PR, will introduce a function in `azalea::Client` i.e. `left_click_mine`, once it is enabled it will make the bot mine the blocks it is looking at if it is within it's range In simpler words, it is a simple left-click implementation for mining blocks.
Although, it is quite basic functionality which could be used either for digging tunnels, mining stones in stone generator, etc. But I thought having it out of the box supported by azalea would be great, that's why I opened this PR.

Added Left Click Mine (1.21)

---

azalea-client/src/mining.rs

This PR, will introduce a function in `azalea::Client` i.e. `left_click_mine`, once it is enabled it will make the bot mine the blocks it is looking at if it is within it's range In simpler words, it is a simple left-click implementation for mining blocks.
Although, it is quite basic functionality which could be used either for digging tunnels, mining stones in stone generator, etc. But I thought having it out of the box supported by azalea would be great, that's why I opened this PR.
The main branch currently, supports Minecraft version `1.21` and introduces changes in `azalea-client/interact.rs` which interferes with `left_click_mine`. This [issue](https://discord.com/channels/1041923016856191016/1041923017317548064/1252128882971246612) makes `left_click_mine` not work in `1.21`. But I …

Added Left Click Mine Functionality

---

azalea-auth/examples/auth_manual.rs
azalea-auth/src/auth.rs
azalea-client/src/account.rs

This PR addresses and closes the issue #130. It introduces two new functions in `azalea_client::Account`:
* `microsoft_with_custom_client_id_and_scope` 
* `with_microsoft_access_token_and_custom_client_id_and_scope`.
This PR will allow the developer, to customize the `client_id` and `scope`, or use the nintendo switch one. Also, some other functions in `auth.rs` like `refresh_ms_auth_token`, `get_ms_link_code`, `interactive_get_ms_auth_token`, etc. are modified and takes some extra parameters now. See the changes in [`auth.rs`](https://github.com/azalea-rs/azalea/pull/159/files#diff-95c725220d95ac22f437570c310f8c41116efd3f4a1876f95cd38455f3bcf63f) for more information.
The existing functions `microsoft` and `with_microsoft_access_token` will maintain their current functionality. However, …

Auth Customization Options

---

azalea-core/src/position.rs

This allows you to `Deserialize` and `Serialize` `BlockPos` and `Vec` with the `serde` feature flag.

Derive Deserialize & Serialize for BlockPos & Vec3

---

azalea-core/src/position.rs

This can parse `X Y Z` back into a `BlockPos` or `Vec3` from the existing `Display` trait.

Impl FromStr for BlockPos & Vec

---

azalea-protocol/src/packets/game/serverbound_use_item_packet.rs

ServerboundUseItemPacket fails to decode because it's missing the yaw and pitch fields that were added in 1.20 or 1.21

Add missing yaw and patch fields to ServerboundUseItemPacket

---

azalea-client/src/chat.rs
azalea-client/src/chunks.rs
azalea-client/src/events.rs
azalea-client/src/lib.rs
azalea-client/src/mining.rs
azalea/src/pathfinder/mod.rs

I think all the internal system handles should be public to resolve conflicts with before/after, but this is the ones that I've needed and changed so far.

Make some internal system handles public for use with before/after

---

azalea-protocol/src/packets/game/clientbound_add_entity_packet.rs

Should entity ids be `i32` instead of `u32` to match Java's int type? I don't know, and it doesn't seem to matter, this was the easier and lesser of the two options to pull request.

Switch to u32 to match other entity ids in Azalea

---

azalea-client/src/packet_handling/configuration.rs

Client will hang because it never reports successfully loading.
Should probably use `ResourcePackEvent` to accept these, but whatever.

Fix accepting ResourcePacks during Configuration

---

azalea-core/src/direction.rs

Derive serde's Serialize and Deserialize for `direction` types when crate's `serde` feature is enabled.
Not a big change but is a continuation of #183 , #179 and #175

chore(core): Derive Serialize and Deserialize for `direction` types

---

.github/workflows/doc.yml

I love azalea, and sometimes I need to use different branch of azalea like `1.20.4`. The issue is that azalea, currently only hosts documentation for `main` branch and though it would be great if it supported documentation multiple branches. This is what this PR introduces.
A Demo is available at https://as1100k.github.io/azalea/ [Old due to changes requested]
1. Create a [orphan branch](https://stackoverflow.com/questions/1384325/in-git-is-there-a-simple-way-of-introducing-an-unrelated-branch-to-a-repository#:~:text=git%20checkout%20%2D%2Dorphan%20newbranch%0Agit%20rm%20%2Drf%20.%0A%3Cdo%20work%3E%0Agit%20add%20your%20files%0Agit%20commit%20%2Dm%20%27Initial%20commit%27) `docs`. And a `Initial Commit` with `.gitignore` with the following content:
```
target
```
2. Update `doc.yml` for …

Feat: Host Documentation for multiple versions/branch

---

azalea-auth/README.md
azalea-client/src/plugins/packet/game/mod.rs
azalea-protocol/README.md
codegen/README.md

Since wiki.vg is now [offline](https://tkte.ch/articles/2024/11/11/sunsetting.html), I've replaced all links with their counterparts on `https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge`

update dead wiki.vg links

---

azalea/src/pathfinder/mod.rs

sometimes the tick broadcaster would lag and would cause the entire thread to panic with `Lagged(1)`

remove `.unwrap()` from `wait_until_goto_target_reached`

---

azalea-chat/src/style.rs

```rust
use azalea_chat::{style::{ChatFormatting, TextColor}, text_component::TextComponent};
use serde_json::value::Serializer;
use serde::Serialize;
fn main() {
let mut t = TextComponent::new("Some content".to_owned());
t.base.style.color = Some(TextColor::try_from(ChatFormatting::Red).unwrap());
println!("{}", TextComponent::serialize(&t, Serializer).unwrap());
}
```
azalea 0.11.0 produces: `{"color":"red","text":"Some content"}`
azalea 0.12.0 produces: `{"color":"RED","text":"Some content"}`
The component produced by 0.12.0 is invalid:

Named TextColor must be lowercase

---

azalea-client/src/plugins/chat/mod.rs

This separates the system chat sender/content splitting regex and adds a system chat whisper regex which can both be overridden to add custom server chat format parsing, the built-in ones support Vanilla and Essentials Chat, and now use capture group names so that really weird formats with out of order groups can still be parsed (such as content, then sender)

Improve System Chat Regex & Add System Whisper Regex

---

azalea/src/container.rs

This change was made so people can actually add systems before or after this

make `handle_menu_opened_event` public
