azalea-rs/azalea

- README.md
- azalea-brigadier/src/lib.rs
- azalea-brigadier/src/suggestion/mod.rs
- azalea-brigadier/src/suggestion/suggestions.rs
- azalea-client/src/client.rs
- azalea-client/src/movement.rs
- azalea-client/src/player.rs
- azalea-physics/src/collision/dimension_collisions.rs
- azalea-physics/src/collision/mod.rs
- azalea-physics/src/lib.rs
- azalea-protocol/src/packets/game/clientbound_add_entity_packet.rs
- azalea-protocol/src/packets/game/clientbound_add_player_packet.rs
- azalea-world/src/entity/mod.rs
- azalea-world/src/entity_storage.rs
- azalea-world/src/lib.rs
Basically make it so entities have a reference to the dimension they're in
> Better entities

- azalea-buf/README.md
- azalea-buf/azalea-buf-macros/src/lib.rs
- azalea-buf/src/lib.rs
- azalea-buf/src/read.rs
- azalea-buf/src/serializable_uuid.rs
- azalea-buf/src/write.rs
- azalea-chat/src/component.rs
- azalea-physics/src/collision/mod.rs
- azalea-protocol/src/packets/game/clientbound_commands_packet.rs
- azalea-protocol/src/packets/game/clientbound_player_abilities_packet.rs
- azalea-protocol/src/packets/game/clientbound_player_info_packet.rs
- azalea-protocol/src/packets/game/clientbound_player_position_packet.rs
- azalea-protocol/src/packets/game/clientbound_update_attributes_packet.rs
- azalea-protocol/src/packets/game/clientbound_update_recipes_packet.rs
- azalea-protocol/src/packets/game/clientbound_update_tags_packet.rs
- azalea-protocol/src/packets/login/clientbound_login_compression_packet.rs
- azalea-protocol/src/packets/mod.rs
- azalea-protocol/src/packets/status/clientbound_status_response_packet.rs
- azalea-protocol/src/read.rs
- azalea-protocol/src/write.rs
- azalea-world/src/palette.rs
The traits weren't really necessary, and I've wanted to get rid of them for a while.
> Get rid of Readable & Writable traits

- azalea-block/src/blocks.rs
- codegen/README.md
- codegen/genblocks.py
- codegen/lib/code/shapes.py
- codegen/lib/download.py
- codegen/lib/extract.py
[It](https://github.com/PrismarineJS/minecraft-data-generator-server) isn't really maintained and [PixLyzer](https://gitlab.bixilon.de/bixilon/pixlyzer) is
> Replace PJS generator mod with PixLyzer

- azalea-protocol/src/connect.rs
this would simplify `Connection<R, W>` grinders
> Military-grade server implementation

- azalea-client/src/client.rs
> feat: PlayerCombatKill client event

- .github/workflows/doc.yml
- rust-toolchain
Added a workflow to automatically document everything
> Uploaded doc workflow

- azalea-client/src/client.rs
Passes messages like "The server is full!" and "Banned by an operator."
Ban reasons are formatted like "You are banned from this server.\nReason: foo"
> Add reason for disconnect

- azalea-client/src/chat.rs
- azalea-client/src/client.rs
- azalea-client/src/events.rs
- azalea-client/src/lib.rs
- azalea-client/src/local_player.rs
- azalea-client/src/packet_handling.rs
- azalea/src/lib.rs
- azalea/src/swarm/chat.rs
- azalea/src/swarm/mod.rs
This basically makes it so you can send chat packets more easily from a plugin, and also moves around some stuff to make more sense.
> Better chat events

- azalea-client/src/packet_handling.rs
- azalea-protocol/src/packets/game/clientbound_block_event_packet.rs
Closes:  ClientboundBlockEventPacket.block is wrong #69
> Block instead of BlockState

- azalea-core/src/block_hit_result.rs
- azalea-core/src/difficulty.rs
- azalea-core/src/game_type.rs
- azalea-protocol/src/packets/game/clientbound_update_tags_packet.rs
- azalea-protocol/src/packets/game/serverbound_chat_ack_packet.rs
- azalea-protocol/src/packets/game/serverbound_chat_packet.rs
- azalea-world/src/lib.rs
And a couple other small things
> Make things public

- Cargo.toml
- azalea-client/Cargo.toml
- azalea-client/src/client.rs
- azalea/Cargo.toml
- azalea/README.md
- azalea/src/lib.rs
https://github.com/mat-1/azalea/issues/92
> Add ClientBuilder:new_without_log

- azalea-auth/src/auth.rs
I don't see why it can't be public so i made it public (i need to use it)
> Make check_ownership pub

- azalea-client/src/raw_connection.rs
> fixes unwrap on write_raw_packet(...)

- Cargo.lock
- azalea-buf/Cargo.toml
- azalea-buf/src/read.rs
- azalea-chat/Cargo.toml
- azalea-chat/src/component.rs
- azalea-chat/src/numbers.rs
- azalea-client/Cargo.toml
- azalea-core/Cargo.toml
- azalea-core/src/registry_holder.rs
- azalea-entity/Cargo.toml
- azalea-inventory/Cargo.toml
- azalea-protocol/Cargo.toml
- azalea-registry/Cargo.toml
- azalea-world/Cargo.toml
Just update simdnb git dep to make using the git dependency work again
> Update simdnbt dep

- azalea-world/src/chunk_storage.rs
This PR fixes #157 opened by me.
The changes are quite simple,
* replace `panic` with `warn` in dev profile
* replace `tracing::error` with `tracing::trace` in release profile
> fix: Chunk Storage Error

- azalea-client/src/lib.rs
- azalea-inventory/src/lib.rs
This PR fixes #166 by making these components/structs public.
> Made `Hunger` and `DataComponentPatch` public

- Cargo.lock
- azalea/Cargo.toml
- azalea/src/pathfinder/goals.rs
I'm storing goals in config files for user configuration and long term state storage.
> Add more derives to the pathfinder goals for flexibility

- azalea-world/src/chunk_storage.rs
Change most to least in debug mode too
> Fix debug warning

- azalea-block/src/behavior.rs
- azalea-block/src/generated.rs
- azalea-client/src/entity_query.rs
- azalea-client/src/plugins/brand.rs
- azalea-core/src/aabb.rs
- azalea-core/src/delta.rs
- azalea-core/src/direction.rs
- azalea-core/src/position.rs
- azalea-entity/src/lib.rs
- azalea-physics/src/clip.rs
- azalea-physics/src/collision/entity_collisions.rs
- azalea-physics/src/collision/mod.rs
- azalea-physics/src/collision/shape.rs
- azalea-physics/src/collision/world_collisions.rs
- azalea-physics/src/fluids.rs
- azalea-physics/src/lib.rs
- azalea-physics/src/travel.rs
- azalea-physics/tests/physics.rs
- azalea-protocol/src/connect.rs
- azalea/src/accept_resource_packs.rs
- codegen/genblocks.py
- codegen/lib/code/blocks.py
- codegen/lib/extract.py
- codegen/lib/mappings.py
- Fixes the bot incorrectly gaining upwards velocity in some cases in fluids
- Fixes the bot being influenced by fluids that are too far by one block in positive coordinate directions.
- Implements force_solid which resolves some problems related to water flowing
> Fluid physics fixes

- azalea-client/src/client.rs
Also runs `App:finish()` after plugins finish loading.
> Wait for plugins to load before starting the ECS

- azalea-chat/src/component.rs
- azalea-chat/src/lib.rs
- azalea-chat/src/style.rs
- azalea-chat/src/text_component.rs
Also fix a small issue with ansi formatting where it duplicated text.
> Implement a to_html method for FormattedText

- azalea/src/pathfinder/goals.rs
idk if what im doing is good or performant so
> add distance param for ReachBlockPosGoal

- azalea-chat/src/component.rs
- azalea-chat/src/translatable_component.rs
Implements the translation fallback key as introduced in [1.19.4](https://minecraft.wiki/w/Java_Edition_1.19.4#Command_format_2)
> Implement text component translation fallback
